CATEGORY_AVERAGES = {
    'India': {
        'serum':       {'avg_price_per_ml': 20.50, 'avg_active_count': 3.5},
        'moisturizer': {'avg_price_per_ml': 15.30, 'avg_active_count': 2.0},
        'cleanser':    {'avg_price_per_ml': 10.00, 'avg_active_count': 1.0},
        'toner':       {'avg_price_per_ml': 12.00, 'avg_active_count': 1.5},
        'sunscreen':   {'avg_price_per_ml': 18.00, 'avg_active_count': 1.0},
        'eye cream':   {'avg_price_per_ml': 40.00, 'avg_active_count': 2.5},
        'mask':        {'avg_price_per_ml': 25.00, 'avg_active_count': 1.5},
        'treatment':   {'avg_price_per_ml': 30.00, 'avg_active_count': 2.5},
        'facial oil':  {'avg_price_per_ml': 25.00, 'avg_active_count': 1.5},
    },
    'USA': {
        'serum':       {'avg_price_per_ml': 0.85, 'avg_active_count': 3.5},
        'moisturizer': {'avg_price_per_ml': 0.55, 'avg_active_count': 2.0},
        'cleanser':    {'avg_price_per_ml': 0.35, 'avg_active_count': 1.0},
        'toner':       {'avg_price_per_ml': 0.40, 'avg_active_count': 1.5},
        'sunscreen':   {'avg_price_per_ml': 0.65, 'avg_active_count': 1.0},
        'eye cream':   {'avg_price_per_ml': 1.50, 'avg_active_count': 2.5},
        'mask':        {'avg_price_per_ml': 0.90, 'avg_active_count': 1.5},
        'treatment':   {'avg_price_per_ml': 1.00, 'avg_active_count': 2.5},
        'oil':         {'avg_price_per_ml': 1.00, 'avg_active_count': 1.5},
    },
    'UK': {
        'serum':       {'avg_price_per_ml': 0.75, 'avg_active_count': 3.5},
        'moisturizer': {'avg_price_per_ml': 0.50, 'avg_active_count': 2.0},
        'cleanser':    {'avg_price_per_ml': 0.30, 'avg_active_count': 1.0},
        'toner':       {'avg_price_per_ml': 0.35, 'avg_active_count': 1.5},
        'sunscreen':   {'avg_price_per_ml': 0.60, 'avg_active_count': 1.0},
        'eye cream':   {'avg_price_per_ml': 1.30, 'avg_active_count': 2.5},
        'mask':        {'avg_price_per_ml': 0.80, 'avg_active_count': 1.5},
        'treatment':   {'avg_price_per_ml': 0.90, 'avg_active_count': 2.5},
        'oil':         {'avg_price_per_ml': 0.90, 'avg_active_count': 1.5},
    },
    'UAE': {
        'serum':       {'avg_price_per_ml': 2.50, 'avg_active_count': 3.5},
        'moisturizer': {'avg_price_per_ml': 1.80, 'avg_active_count': 2.0},
        'cleanser':    {'avg_price_per_ml': 1.20, 'avg_active_count': 1.0},
        'toner':       {'avg_price_per_ml': 1.40, 'avg_active_count': 1.5},
        'sunscreen':   {'avg_price_per_ml': 2.00, 'avg_active_count': 1.0},
        'eye cream':   {'avg_price_per_ml': 5.00, 'avg_active_count': 2.5},
        'mask':        {'avg_price_per_ml': 2.80, 'avg_active_count': 1.5},
        'treatment':   {'avg_price_per_ml': 3.50, 'avg_active_count': 2.5},
        'oil':         {'avg_price_per_ml': 3.00, 'avg_active_count': 1.5},
    },
    'Singapore': {
        'serum':       {'avg_price_per_ml': 1.80, 'avg_active_count': 3.5},
        'moisturizer': {'avg_price_per_ml': 1.30, 'avg_active_count': 2.0},
        'cleanser':    {'avg_price_per_ml': 0.90, 'avg_active_count': 1.0},
        'toner':       {'avg_price_per_ml': 1.00, 'avg_active_count': 1.5},
        'sunscreen':   {'avg_price_per_ml': 1.50, 'avg_active_count': 1.0},
        'eye cream':   {'avg_price_per_ml': 3.50, 'avg_active_count': 2.5},
        'mask':        {'avg_price_per_ml': 2.00, 'avg_active_count': 1.5},
        'treatment':   {'avg_price_per_ml': 2.50, 'avg_active_count': 2.5},
        'oil':         {'avg_price_per_ml': 2.00, 'avg_active_count': 1.5},
    },
    'Australia': {
        'serum':       {'avg_price_per_ml': 1.20, 'avg_active_count': 3.5},
        'moisturizer': {'avg_price_per_ml': 0.85, 'avg_active_count': 2.0},
        'cleanser':    {'avg_price_per_ml': 0.55, 'avg_active_count': 1.0},
        'toner':       {'avg_price_per_ml': 0.65, 'avg_active_count': 1.5},
        'sunscreen':   {'avg_price_per_ml': 1.00, 'avg_active_count': 1.0},
        'eye cream':   {'avg_price_per_ml': 2.20, 'avg_active_count': 2.5},
        'mask':        {'avg_price_per_ml': 1.30, 'avg_active_count': 1.5},
        'treatment':   {'avg_price_per_ml': 1.60, 'avg_active_count': 2.5},
        'oil':         {'avg_price_per_ml': 1.20, 'avg_active_count': 1.5},
    },
    'Canada': {
        'serum':       {'avg_price_per_ml': 0.90, 'avg_active_count': 3.5},
        'moisturizer': {'avg_price_per_ml': 0.65, 'avg_active_count': 2.0},
        'cleanser':    {'avg_price_per_ml': 0.40, 'avg_active_count': 1.0},
        'toner':       {'avg_price_per_ml': 0.45, 'avg_active_count': 1.5},
        'sunscreen':   {'avg_price_per_ml': 0.70, 'avg_active_count': 1.0},
        'eye cream':   {'avg_price_per_ml': 1.60, 'avg_active_count': 2.5},
        'mask':        {'avg_price_per_ml': 1.00, 'avg_active_count': 1.5},
        'treatment':   {'avg_price_per_ml': 1.10, 'avg_active_count': 2.5},
        'oil':         {'avg_price_per_ml': 1.00, 'avg_active_count': 1.5},
    },
    'South Korea': {
        'serum':       {'avg_price_per_ml': 0.70, 'avg_active_count': 4.0},
        'moisturizer': {'avg_price_per_ml': 0.50, 'avg_active_count': 2.5},
        'cleanser':    {'avg_price_per_ml': 0.30, 'avg_active_count': 1.0},
        'toner':       {'avg_price_per_ml': 0.25, 'avg_active_count': 2.0},
        'sunscreen':   {'avg_price_per_ml': 0.55, 'avg_active_count': 1.0},
        'eye cream':   {'avg_price_per_ml': 1.20, 'avg_active_count': 2.5},
        'mask':        {'avg_price_per_ml': 0.60, 'avg_active_count': 1.5},
        'treatment':   {'avg_price_per_ml': 0.80, 'avg_active_count': 2.5},
        'oil':         {'avg_price_per_ml': 0.70, 'avg_active_count': 1.5},
    },
    'Japan': {
        'serum':       {'avg_price_per_ml': 1.00, 'avg_active_count': 3.5},
        'moisturizer': {'avg_price_per_ml': 0.70, 'avg_active_count': 2.0},
        'cleanser':    {'avg_price_per_ml': 0.45, 'avg_active_count': 1.0},
        'toner':       {'avg_price_per_ml': 0.35, 'avg_active_count': 2.0},
        'sunscreen':   {'avg_price_per_ml': 0.80, 'avg_active_count': 1.5},
        'eye cream':   {'avg_price_per_ml': 1.80, 'avg_active_count': 2.5},
        'mask':        {'avg_price_per_ml': 0.90, 'avg_active_count': 1.5},
        'treatment':   {'avg_price_per_ml': 1.20, 'avg_active_count': 2.5},
        'oil':         {'avg_price_per_ml': 1.00, 'avg_active_count': 1.5},
    },
    'France': {
        'serum':       {'avg_price_per_ml': 1.10, 'avg_active_count': 3.0},
        'moisturizer': {'avg_price_per_ml': 0.75, 'avg_active_count': 2.0},
        'cleanser':    {'avg_price_per_ml': 0.40, 'avg_active_count': 1.0},
        'toner':       {'avg_price_per_ml': 0.45, 'avg_active_count': 1.5},
        'sunscreen':   {'avg_price_per_ml': 0.80, 'avg_active_count': 1.0},
        'eye cream':   {'avg_price_per_ml': 1.80, 'avg_active_count': 2.5},
        'mask':        {'avg_price_per_ml': 1.00, 'avg_active_count': 1.5},
        'treatment':   {'avg_price_per_ml': 1.20, 'avg_active_count': 2.5},
        'oil':         {'avg_price_per_ml': 1.10, 'avg_active_count': 1.5},
    },
    'Germany': {
        'serum':       {'avg_price_per_ml': 0.95, 'avg_active_count': 3.0},
        'moisturizer': {'avg_price_per_ml': 0.65, 'avg_active_count': 2.0},
        'cleanser':    {'avg_price_per_ml': 0.35, 'avg_active_count': 1.0},
        'toner':       {'avg_price_per_ml': 0.40, 'avg_active_count': 1.5},
        'sunscreen':   {'avg_price_per_ml': 0.70, 'avg_active_count': 1.0},
        'eye cream':   {'avg_price_per_ml': 1.50, 'avg_active_count': 2.5},
        'mask':        {'avg_price_per_ml': 0.90, 'avg_active_count': 1.5},
        'treatment':   {'avg_price_per_ml': 1.00, 'avg_active_count': 2.5},
        'oil':         {'avg_price_per_ml': 0.90, 'avg_active_count': 1.5},
    },
    'Brazil': {
        'serum':       {'avg_price_per_ml': 1.50, 'avg_active_count': 2.5},
        'moisturizer': {'avg_price_per_ml': 1.00, 'avg_active_count': 1.5},
        'cleanser':    {'avg_price_per_ml': 0.60, 'avg_active_count': 1.0},
        'toner':       {'avg_price_per_ml': 0.70, 'avg_active_count': 1.5},
        'sunscreen':   {'avg_price_per_ml': 1.20, 'avg_active_count': 1.0},
        'eye cream':   {'avg_price_per_ml': 3.00, 'avg_active_count': 2.0},
        'mask':        {'avg_price_per_ml': 1.50, 'avg_active_count': 1.5},
        'treatment':   {'avg_price_per_ml': 2.00, 'avg_active_count': 2.0},
        'oil':         {'avg_price_per_ml': 1.50, 'avg_active_count': 1.5},
    },
}

CATEGORY_AVERAGES_DEFAULT = CATEGORY_AVERAGES['India']

WORTH_MULTIPLIERS = {
    'Concentration Transparency': 1.5,
    'Stability Engineering': 2.0,
    'Barrier Neutrality': 1.3,
}

WORTH_RED_FLAGS = {
    'Fragrance': -20,
    'Essential Oils': -15,
    'Alcohol Denat': -15,
    'High Irritation': -15,
}

CONCENTRATION_THRESHOLDS = {
    'Phenoxyethanol': 1.0,
    'Xanthan Gum': 1.0,
    'Carbomer': 1.0,
    'Disodium EDTA': 0.1,
    'Tocopherol': 0.5,
    'Sodium Benzoate': 1.0,
    'Potassium Sorbate': 1.0,
    'Ethylhexylglycerin': 1.0,
    'Methylparaben': 0.5,
    'Propylparaben': 0.5,
    'Chlorphenesin': 0.5,
}

CONCERNS_MAP = {
    'Acne & Oily Skin':  ['Salicylic Acid', 'Benzoyl Peroxide', 'Azelaic Acid', 'Niacinamide', 'Retinol', 'Zinc PCA'],
    'Pigmentation':      ['Tranexamic Acid', 'Azelaic Acid', 'Alpha Arbutin', 'Niacinamide', 'Ascorbic Acid', 'Kojic Acid'],
    'Aging & Fine Lines': ['Retinol', 'Retinal', 'Peptides', 'Ascorbic Acid', 'Glycolic Acid', 'Bakuchiol'],
    'Barrier Repair':    ['Ceramide', 'Cholesterol', 'Fatty Acid', 'Panthenol', 'Niacinamide'],
    'Sensitive Skin':    ['Centella Asiatica', 'Panthenol', 'Allantoin', 'Ceramide', 'Madecassoside'],
    'Hydration':         ['Sodium Hyaluronate', 'Glycerin', 'Panthenol', 'Sodium PCA', 'Urea'],
    'Large Pores':       ['Niacinamide', 'Salicylic Acid', 'Retinol', 'Glycolic Acid'],
    'Dullness':          ['Ascorbic Acid', 'Niacinamide', 'Glycolic Acid', 'Licorice Extract'],
    'Uneven Texture':    ['Glycolic Acid', 'Salicylic Acid', 'Retinol', 'Lactic Acid'],
    'Dark Circles':      ['Caffeine', 'Vitamin K', 'Ascorbic Acid', 'Peptides', 'Niacinamide'],
    'Sun Protection':    ['Zinc Oxide', 'Titanium Dioxide', 'Avobenzone', 'Octinoxate', 'Homosalate', 'Bemotrizinol'],
    'UV Damage':         ['Ferulic Acid', 'Polypodium Leucotomos', 'Ascorbic Acid', 'Astaxanthin', 'Resveratrol', 'Green Tea Extract'],
    'Tanning':           ['Alpha Arbutin', 'Kojic Acid', 'Tranexamic Acid', 'Ascorbic Acid', 'Niacinamide', 'Glutathione'],
    'Puffiness':         ['Caffeine', 'Acetyl Tetrapeptide-5', 'Hesperidin Methyl Chalcone', 'Niacinamide', 'Centella Asiatica'],
}

SUPPORTING_KEYWORDS = {
    'Acne & Oily Skin': ['zinc', 'glycerin', 'centella', 'panthenol', 'pentylene glycol', 'tea tree'],
    'Pigmentation':     ['glycerin', 'ferulic', 'vitamin e', 'panthenol', 'licorice'],
    'Aging & Fine Lines': ['niacinamide', 'hyaluronic', 'ceramide', 'ferulic', 'peptide'],
    'Barrier Repair':   ['glycerin', 'sodium hyaluronate', 'allantoin', 'bisabolol', 'fatty acid', 'squalane'],
    'Sensitive Skin':   ['glycerin', 'sodium hyaluronate', 'bisabolol', 'allantoin', 'niacinamide'],
    'Hydration':        ['ceramide', 'squalane', 'niacinamide', 'betaine', 'sodium pca'],
    'Large Pores':      ['zinc', 'glycerin', 'centella', 'panthenol', 'pentylene glycol'],
    'Dullness':         ['vitamin e', 'ferulic', 'panthenol', 'niacinamide'],
    'Uneven Texture':   ['niacinamide', 'panthenol', 'centella', 'urea', 'ceramide'],
    'Dark Circles':     ['hyaluronic', 'glycerin', 'ceramide', 'niacinamide'],
    'Sun Protection':   ['ferulic acid', 'vitamin e', 'niacinamide', 'green tea', 'antioxidant'],
    'UV Damage':        ['vitamin e', 'niacinamide', 'ceramide', 'panthenol', 'centella'],
    'Tanning':          ['ferulic', 'vitamin e', 'panthenol', 'glycerin', 'licorice'],
    'Puffiness':        ['hyaluronic', 'glycerin', 'allantoin', 'panthenol', 'green tea'],
}

WORSENING_INGREDIENTS = {
    'Acne & Oily Skin': [('isopropyl myristate', -10), ('coconut oil', -10), ('fragrance', -5), ('cocos nucifera', -10), ('lanolin', -8)],
    'Sensitive Skin':   [('fragrance', -15), ('parfum', -15), ('alcohol denat', -15), ('essential oil', -10), ('limonene', -8), ('linalool', -8)],
    'Barrier Repair':   [('sodium lauryl sulfate', -10), ('alcohol denat', -10), ('fragrance', -8), ('parfum', -8)],
    'Pigmentation':     [('limonene', -5), ('linalool', -5), ('fragrance', -5), ('bergamot', -8)],
    'Hydration':        [('alcohol denat', -10), ('sd alcohol', -10), ('isopropyl alcohol', -8)],
    # Previously missing - now added
    'Aging & Fine Lines': [('fragrance', -8), ('parfum', -8), ('alcohol denat', -8), ('sd alcohol', -8), ('limonene', -5), ('linalool', -5)],
    'Large Pores':        [('isopropyl myristate', -10), ('coconut oil', -8), ('cocos nucifera', -8), ('fragrance', -5)],
    'Dullness':           [('fragrance', -5), ('parfum', -5), ('limonene', -8), ('linalool', -8), ('bergamot', -8)],
    'Uneven Texture':     [('fragrance', -5), ('parfum', -5), ('alcohol denat', -5)],
    'Dark Circles':       [('fragrance', -5), ('parfum', -5), ('sodium lauryl sulfate', -5)],
    'Sun Protection':     [('alcohol denat', -8), ('sd alcohol', -8), ('fragrance', -5)],
    'UV Damage':          [('fragrance', -5), ('parfum', -5), ('limonene', -8), ('linalool', -8)],
    'Tanning':            [('fragrance', -5), ('parfum', -5), ('limonene', -10), ('bergamot', -10)],
    'Puffiness':          [('fragrance', -5), ('parfum', -5), ('alcohol denat', -5)],
}

COUNTRY_CURRENCY_MAP = {
    'India': 'INR', 'USA': 'USD', 'UK': 'GBP', 'UAE': 'AED',
    'Singapore': 'SGD', 'Australia': 'AUD', 'Canada': 'CAD',
    'South Korea': 'KRW', 'Japan': 'JPY', 'France': 'EUR',
    'Germany': 'EUR', 'Brazil': 'BRL',
}

SHOPPING_SITES = {
    'India': ['Amazon.in', 'Nykaa', 'Flipkart', 'Purple', 'Myntra'],
    'USA': ['Amazon.com', 'Sephora', 'Ulta', 'Target', 'Walmart'],
    'UK': ['Boots', 'Lookfantastic', 'Cult Beauty', 'Superdrug'],
    'Canada': ['Amazon.ca', 'Shoppers Drug Mart'],
    'Australia': ['Priceline', 'Adore Beauty', 'Amazon.au'],
    'UAE': ['Noon', 'Amazon.ae', 'Faces'],
    'Singapore': ['Sephora Singapore', 'Lazada', 'Guardian'],
    'South Korea': ['Olive Young', 'Coupang', 'Amazon.kr'],
    'Japan': ['Amazon.co.jp', 'Cosme', 'Rakuten'],
    'France': ['Sephora.fr', 'Nocibe', 'Pharmacie'],
    'Germany': ['Douglas', 'Notino', 'DM'],
    'Brazil': ['Beleza na Web', 'Sephora.com.br', 'Amazon.com.br'],
}
